# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

operator:
  image:
    repository: cgr.dev/du-uds-defenseunicorns/minio-operator-fips
    tag: "7.0.1"
  sidecarImage:
    repository: cgr.dev/du-uds-defenseunicorns/minio-operator-sidecar
    tag: "7.0.1"
    pullPolicy: IfNotPresent
