# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tenant:
  image:
    repository: quay.io/rfcurated/minio/minio
    # renovate: datasource=docker depName=quay.io/rfcurated/minio/minio versioning=regex:^RELEASE\.(?<major>\d+)-(?<minor>\d+)-(?<patch>\d+)T(?<build>\d+)-(?<revision>\d+)Z-jammy-scratch-fips-rfcurated$
    tag: RELEASE.2025-07-23T15-54-02Z-jammy-scratch-fips-rfcurated
    pullPolicy: IfNotPresent
